apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

# Reference the new base directory
resources:
- ../../base

# Add production-specific labels

# Add production-specific annotations
commonAnnotations:
  app.kubernetes.io/environment: production

# Patches for production environment
labels:
- includeSelectors: true
  pairs:
    environment: production
patches:
- path: resource-limits.yaml
