apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-config
  namespace: arbatross
data:
  nginx.conf: |
    server {
        listen 80;
        server_name localhost;

        root /usr/share/nginx/html;
        index index.html;

        location / {
            try_files $uri $uri/ /index.html;
        }

        location /styles.css {
            try_files $uri =404;
        }

        location /widgets/ {
            try_files $uri =404;
        }

        # Proxy to diff-eye
        location /exchanges {
            proxy_pass http://diff-eye:8000;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
        }

        location /ws {
            proxy_pass http://diff-eye:8000;
            proxy_http_version 1.1;
            proxy_set_header Upgrade $http_upgrade;
            proxy_set_header Connection "upgrade";
            proxy_set_header Host $host;
        }

        # Proxy to voltic-eye
        location /volatility/top-volatile {
            proxy_pass http://voltic-eye:8001;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
        }

        location /volatility/ws {
            proxy_pass http://voltic-eye:8001/ws;
            proxy_http_version 1.1;
            proxy_set_header Upgrade $http_upgrade;
            proxy_set_header Connection "upgrade";
            proxy_set_header Host $host;
        }
    }
