apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: arbatross

resources:
- namespace.yaml
- configmap.yaml
- diff-eye-deployment.yaml
- voltic-eye-deployment.yaml
- frontend-deployment.yaml
- ingress.yaml


commonAnnotations:
  app.kubernetes.io/version: 1.0.0
labels:
- includeSelectors: true
  pairs:
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/part-of: arbatross
