apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

# Reference the base directory
resources:
- ../../base

# Add dev-specific labels

# Add dev-specific annotations
commonAnnotations:
  app.kubernetes.io/environment: development
labels:
- includeSelectors: true
  pairs:
    environment: development
